const seedPlaces=[
{id:'p1',name:'강릉 바다 창가 카페',category:'카페',memo:'창가 자리에서 바다가 잘 보였고 평일 오전에는 사람이 적었음',tags:['바다전망','다시갈곳'],date:'2026-05-18',lat:37.772,lng:128.947,collection:'c1',privacy:'private',image:''},
{id:'p2',name:'성수동 소품숍',category:'쇼핑',memo:'선물하기 좋았던 가죽가방을 발견함',tags:['쇼핑','선물'],date:'2026-07-24',lat:37.544,lng:127.056,collection:'c3',privacy:'private',image:''},
{id:'p3',name:'제주 조용한 해변',category:'볼거리',memo:'사람이 적고 노을이 예뻤음',tags:['바다','노을'],date:'2026-07-11',lat:33.45,lng:126.31,collection:'c1',privacy:'link',image:''},
{id:'p4',name:'전주 한옥 베이커리',category:'카페',memo:'마당과 빵이 모두 좋았음',tags:['카페','한옥'],date:'2026-07-02',lat:35.815,lng:127.153,collection:'c2',privacy:'private',image:''}
];
const seedCollections=[
{id:'c1',name:'제주·강릉 다시 갈 곳',privacy:'link'},
{id:'c2',name:'가족과 갈 식당',privacy:'private'},
{id:'c3',name:'사고 싶은 물건 판매처',privacy:'private'},
{id:'c4',name:'캠핑하기 좋은 장소',privacy:'link'}
];
const state={tab:'map',places:JSON.parse(localStorage.getItem('yyj_places')||'null')||seedPlaces,collections:JSON.parse(localStorage.getItem('yyj_collections')||'null')||seedCollections,selectedId:'p1',filter:'전체',pendingImage:''};
const $=s=>document.querySelector(s); const view=$('#view');
function save(){localStorage.setItem('yyj_places',JSON.stringify(state.places));localStorage.setItem('yyj_collections',JSON.stringify(state.collections));}
function toast(message){const t=document.createElement('div');t.className='toast';t.textContent=message;document.body.appendChild(t);setTimeout(()=>t.remove(),2500)}
function setHeader(title,eyebrow){$('#headerTitle').textContent=title;$('#headerEyebrow').textContent=eyebrow}
function formatDate(date){return new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric'}).format(new Date(date))}
function photoStyle(place){return place.image?`style="background-image:url('${place.image}')"`:''}
function thumb(place){return `<div class="thumb" ${photoStyle(place)}></div>`}
function openDetail(id){const p=state.places.find(v=>v.id===id);if(!p)return;const col=state.collections.find(c=>c.id===p.collection);const d=$('#detailDialog');d.innerHTML=`<div class="detail-hero" ${photoStyle(p)}><button class="icon-button detail-close" onclick="detailDialog.close()">✕</button></div><div class="detail-body"><p class="meta">${p.category} · ${formatDate(p.date)}</p><h2>${p.name}</h2><p>${p.memo||'아직 메모가 없습니다.'}</p><p class="tags">${p.tags.map(t=>'#'+t).join(' ')}</p><p class="meta">⌖ ${p.lat||'-'}, ${p.lng||'-'}<br>▣ ${col?.name||'컬렉션 없음'} · ${p.privacy==='private'?'나만 보기':'링크 공유'}</p><div class="detail-actions"><button class="secondary" onclick="sharePlace('${p.id}')">공유</button><button class="primary" onclick="deletePlace('${p.id}')">삭제</button></div></div>`;d.showModal()}
window.detailDialog=$('#detailDialog');
window.sharePlace=async id=>{const p=state.places.find(v=>v.id===id);const text=`${p.name}\n${p.memo}\n위치: ${p.lat}, ${p.lng}`;try{if(navigator.share)await navigator.share({title:p.name,text});else await navigator.clipboard.writeText(text);toast('공유 내용이 준비되었습니다.')}catch{}}
window.deletePlace=id=>{if(!confirm('이 장소를 삭제할까요?'))return;state.places=state.places.filter(p=>p.id!==id);save();detailDialog.close();render();toast('장소를 삭제했습니다.')}
function renderMap(){setHeader('내 지도',`기억해 둔 장소 ${state.places.length}곳`);view.innerHTML=$('#mapViewTemplate').innerHTML;const categories=['전체',...new Set(state.places.map(p=>p.category))];$('#mapChips').innerHTML=categories.map(c=>`<button class="chip ${state.filter===c?'active':''}" data-filter="${c}">${c}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderMap()});
const filtered=state.places.filter(p=>state.filter==='전체'||p.category===state.filter);$('#pins').innerHTML=filtered.map((p,i)=>`<button class="pin ${state.selectedId===p.id?'active':''}" data-pin="${p.id}" style="left:${35+(i*71)%300}px;top:${55+(i*93)%310}px" aria-label="${p.name}"></button>`).join('');document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>{state.selectedId=b.dataset.pin;renderMap()});const selected=state.places.find(p=>p.id===state.selectedId)||filtered[0];$('#mapSelectedCard').innerHTML=selected?`<article class="place-card" data-detail="${selected.id}">${thumb(selected)}<div><h3>${selected.name}</h3><p>${selected.category} · ${formatDate(selected.date)}</p><p>${selected.memo}</p><p class="tags">${selected.tags.map(t=>'#'+t).join(' ')}</p></div></article>`:'<div class="empty">저장된 장소가 없습니다.</div>';document.querySelector('[data-detail]')?.addEventListener('click',e=>openDetail(e.currentTarget.dataset.detail));$('#mapSearch').oninput=e=>{const q=e.target.value.trim().toLowerCase();const hit=state.places.find(p=>[p.name,p.memo,...p.tags].join(' ').toLowerCase().includes(q));if(hit){state.selectedId=hit.id;$('#mapSelectedCard').innerHTML=`<article class="place-card" data-detail="${hit.id}">${thumb(hit)}<div><h3>${hit.name}</h3><p>${hit.category}</p><p>${hit.memo}</p><p class="tags">${hit.tags.map(t=>'#'+t).join(' ')}</p></div></article>`;document.querySelector('[data-detail]').onclick=()=>openDetail(hit.id)}}}
function renderMemories(){setHeader('기억','사진과 날짜로 다시 찾기');view.innerHTML=$('#memoriesViewTemplate').innerHTML;const list=[...state.places].sort((a,b)=>b.date.localeCompare(a.date));$('#memoryList').innerHTML=list.length?`<h2 class="month-label">${new Date(list[0].date).getFullYear()}년 기억</h2>`+list.map(p=>`<article class="memory-card" data-detail="${p.id}">${thumb(p)}<div><h3>${p.name}</h3><p>${formatDate(p.date)} · ${p.category}</p><p>${p.memo}</p><p class="tags">${p.tags.map(t=>'#'+t).join(' ')}</p></div></article>`).join(''):'<div class="empty">첫 장소를 저장해 보세요.</div>';document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>openDetail(x.dataset.detail))}
function renderAdd(){setHeader('장소 저장','사진과 위치로 기억 남기기');view.innerHTML=$('#addViewTemplate').innerHTML;$('#collectionSelect').innerHTML=state.collections.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');const photo=$('#photoInput');$('#photoButton').onclick=()=>photo.click();photo.onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{state.pendingImage=r.result;const p=$('#photoPreview');p.style.backgroundImage=`url('${r.result}')`;p.innerHTML=''};r.readAsDataURL(file)};$('#locationButton').onclick=()=>{if(!navigator.geolocation){toast('이 기기에서는 위치를 사용할 수 없습니다.');return}navigator.geolocation.getCurrentPosition(pos=>{$('#latitude').value=pos.coords.latitude.toFixed(6);$('#longitude').value=pos.coords.longitude.toFixed(6);toast('현재 위치를 불러왔습니다.')},()=>toast('위치 권한을 허용해 주세요.'),{enableHighAccuracy:true,timeout:8000})};$('#placeForm').onsubmit=e=>{e.preventDefault();const p={id:'p'+Date.now(),name:$('#placeName').value.trim(),category:$('#category').value,memo:$('#memo').value.trim(),tags:$('#tags').value.split(',').map(v=>v.trim()).filter(Boolean),date:new Date().toISOString().slice(0,10),lat:Number($('#latitude').value)||null,lng:Number($('#longitude').value)||null,collection:$('#collectionSelect').value,privacy:document.querySelector('[name=privacy]:checked').value,image:state.pendingImage};state.places.unshift(p);state.selectedId=p.id;state.pendingImage='';save();state.tab='map';syncNav();render();toast('장소를 저장했습니다.')}}
function renderCollections(){setHeader('컬렉션','장소를 주제별로 정리');view.innerHTML=$('#collectionsViewTemplate').innerHTML;$('#collectionList').innerHTML=state.collections.map((c,i)=>{const ps=state.places.filter(p=>p.collection===c.id);const cover=ps[0]||{};return`<article class="collection-card" data-col="${c.id}"><div class="thumb" ${cover.image?`style="background-image:url('${cover.image}')"`:''}></div><div><h3>${c.name}</h3><p>${ps.length}곳 · ${c.privacy==='private'?'나만 보기':'링크 공유'}</p><p class="tags">최근 저장 ${ps[0]?formatDate(ps[0].date):'없음'}</p></div></article>`}).join('');document.querySelectorAll('[data-col]').forEach(el=>el.onclick=()=>{const c=state.collections.find(v=>v.id===el.dataset.col);const ps=state.places.filter(p=>p.collection===c.id);view.innerHTML=`<button class="secondary" id="backCols">‹ 컬렉션</button><h2>${c.name}</h2><p>${ps.length}곳 · ${c.privacy==='private'?'나만 보기':'링크 공유'}</p><div class="memory-list">${ps.map(p=>`<article class="memory-card" data-detail="${p.id}">${thumb(p)}<div><h3>${p.name}</h3><p>${p.memo}</p><p class="tags">${p.tags.map(t=>'#'+t).join(' ')}</p></div></article>`).join('')||'<div class="empty">아직 장소가 없습니다.</div>'}</div>`;$('#backCols').onclick=renderCollections;document.querySelectorAll('[data-detail]').forEach(x=>x.onclick=()=>openDetail(x.dataset.detail))});$('#newCollectionButton').onclick=()=>{const name=prompt('새 컬렉션 이름을 입력하세요.');if(!name?.trim())return;state.collections.push({id:'c'+Date.now(),name:name.trim(),privacy:'private'});save();renderCollections();toast('컬렉션을 만들었습니다.')}}
function render(){({map:renderMap,memories:renderMemories,add:renderAdd,collections:renderCollections}[state.tab]||renderMap)()}
function syncNav(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab))}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;syncNav();render();window.scrollTo({top:0,behavior:'smooth'})});
$('#profileButton').onclick=()=>{const d=$('#settingsDialog');d.innerHTML='<h2>여기였지</h2><p>기능형 프로토타입</p><div class="settings-list"><button id="exportButton">데이터 백업 파일 만들기</button><button id="resetButton">샘플 데이터로 초기화</button><button onclick="settingsDialog.close()">닫기</button></div>';d.showModal();$('#exportButton').onclick=()=>{const blob=new Blob([JSON.stringify({places:state.places,collections:state.collections},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='여기였지-백업.json';a.click();URL.revokeObjectURL(a.href)};$('#resetButton').onclick=()=>{localStorage.clear();location.reload()}};
window.settingsDialog=$('#settingsDialog');
if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
render();
